trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals $(agentName)

variables:
  imageName: 'mangobear/firstrepo'
  agentName: 'Simons-MacBook-Pro'

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile
 - task: Docker@2
   inputs:
     containerRegistry: 'docker registry'
     repository: 'mangobear/firstrepo'
     command: 'push'